version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  discovery:
    build:
      context: ./DiscoveryServer/DiscoveryServer/
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - db
  challengepdv:
    build:
      context: ./ChallengePDV/
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - discovery
  acreditaciones:
    build:
      context: ./acreditaciones/
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - discovery
  apigateway:
    build:
      context: ./ApiGateway/ApiGateway/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - challengepdv
      - acreditaciones
  