services:
  discovery-server:
    container_name: discovery-server
    build:
      context: ./DiscoveryServer/DiscoveryServer/
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    restart:
      always
    networks:
      - springcloud
  mysql8:
    container_name: mysql8
    image: mysql:8.0.40
    ports:
      - "3307:3306"
    restart: always
    networks:
      - springcloud
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_ROOT_PASSWORD: 1234
  challenge-pdv:
    container_name: challenge-pdv
    build:
      context: ./ChallengePDV/
      dockerfile: Dockerfile
    restart: always
    networks:
      - springcloud
    depends_on:
      - discovery-server
      - mysql8
  acreditaciones:
    container_name: acreditaciones
    build:
      context: ./acreditaciones/
      dockerfile: Dockerfile
    restart: always
    networks:
      - springcloud
    depends_on:
      - challenge-pdv
  apigateway:
    container_name: api-gateway
    build:
      context: ./ApiGateway/ApiGateway/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    networks:
      - springcloud
    depends_on:
      - challenge-pdv
      - acreditaciones
networks:
  springcloud: