INSERT INTO PUNTOS (id,name) VALUES (default,'CABA');
INSERT INTO PUNTOS (id,name) VALUES (default,'GBA_1');
INSERT INTO PUNTOS (id, name) VALUES (default, 'GBA_2');
INSERT INTO PUNTOS (id, name) VALUES (default, 'Santa Fe');
INSERT INTO PUNTOS (id, name) VALUES (default, 'Córdoba');
INSERT INTO PUNTOS (id, name) VALUES (default, 'Misiones');
INSERT INTO PUNTOS (id, name) VALUES (default, 'Salta');
INSERT INTO PUNTOS (id, name) VALUES (default, 'Chubut');
INSERT INTO PUNTOS (id, name) VALUES (default, 'Santa Cruz');
INSERT INTO PUNTOS (id, name) VALUES (default, 'Catamarca');
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (1, 2, 2);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (1, 3, 3);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (2, 3, 5);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (2, 4, 10);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (1, 4, 11);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (4, 5, 5);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (2, 5, 14);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (6, 7, 32);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (8, 9, 11);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (10, 7, 5);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (3, 8, 10);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (5, 8, 30);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (10, 5, 5);
INSERT INTO COSTOS (origin_id, destination_id, price) VALUES (4, 6, 6);