INSERT INTO PUNTOS (id,nombre) VALUES (1,'CABA');
INSERT INTO PUNTOS (id,nombre) VALUES (2,'GBA_1');
INSERT INTO PUNTOS (id, nombre) VALUES (3, 'GBA_2');
INSERT INTO PUNTOS (id, nombre) VALUES (4, 'Santa Fe');
INSERT INTO PUNTOS (id, nombre) VALUES (5, 'Córdoba');
INSERT INTO PUNTOS (id, nombre) VALUES (6, 'Misiones');
INSERT INTO PUNTOS (id, nombre) VALUES (7, 'Salta');
INSERT INTO PUNTOS (id, nombre) VALUES (8, 'Chubut');
INSERT INTO PUNTOS (id, nombre) VALUES (9, 'Santa Cruz');
INSERT INTO PUNTOS (id, nombre) VALUES (10, 'Catamarca');
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (1, 2, 2);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (1, 3, 3);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (2, 3, 5);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (2, 4, 10);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (1, 4, 11);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (4, 5, 5);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (2, 5, 14);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (6, 7, 32);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (8, 9, 11);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (10, 7, 5);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (3, 8, 10);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (5, 8, 30);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (10, 5, 5);
INSERT INTO COSTOS (origen_id, destino_id, costo) VALUES (4, 6, 6);